package org.fribok.bookkeeping.dataformat;
import org.junit.jupiter.api.Test;
import se.swedsoft.bookkeeping.data.*;
import se.swedsoft.bookkeeping.data.common.SSHeadingType;
import se.swedsoft.bookkeeping.gui.ownreport.util.SSOwnReportAccountRow;
import java.io.InputStream;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.sql.*;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;
class OwnReportStagingConverterTest{
 @Test void roundTripsHeadingsAccountsAndBudgets()throws Exception{try(Connection legacy=conn("report_legacy");Connection target=conn("report_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany company=new SSNewCompany();company.setId(1);insertCompany(legacy,company);SSNewProject project=new SSNewProject("P1","Project",null);insertScoped(legacy,"tbl_project","project","P1",project);
   SSOwnReport report=report();try(var p=legacy.prepareStatement("INSERT INTO tbl_ownreport (id,ownreport,companyid) VALUES (?,?,?)")){p.setInt(1,1);p.setObject(2,report);p.setInt(3,1);p.executeUpdate();legacy.commit();}
   new AccountingCoreStagingConverter().convert(legacy,target);new AccountingDimensionsStagingConverter().convert(legacy,target);
   var result=new OwnReportStagingConverter().convert(legacy,target);
   assertThat(result.sourceFingerprint()).isEqualTo(result.destinationFingerprint());assertThat(result.reports()).isEqualTo(1);assertThat(result.headings()).isEqualTo(2);assertThat(result.accountRows()).isEqualTo(2);assertThat(result.budgets()).isEqualTo(2);
   assertThat(count(target,"own_report")).isEqualTo(1);assertThat(count(target,"own_report_account_row")).isEqualTo(2);assertThat(count(target,"own_report_account_budget")).isEqualTo(2);}}
 @Test void emptyReportRoundTrips()throws Exception{try(Connection legacy=conn("report_empty_legacy");Connection target=conn("report_empty_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany c=new SSNewCompany();c.setId(1);insertCompany(legacy,c);SSOwnReport x=new SSOwnReport();x.setId(5);x.setName(null);x.setProjectNr(null);x.setResultUnitNr(null);try(var p=legacy.prepareStatement("INSERT INTO tbl_ownreport (id,ownreport,companyid) VALUES (?,?,?)")){p.setInt(1,1);p.setObject(2,x);p.setInt(3,1);p.executeUpdate();legacy.commit();}new AccountingCoreStagingConverter().convert(legacy,target);var result=new OwnReportStagingConverter().convert(legacy,target);assertThat(result.sourceFingerprint()).isEqualTo(result.destinationFingerprint());assertThat(result.reports()).isEqualTo(1);assertThat(result.headings()).isZero();}}
 private static SSOwnReport report(){SSOwnReport x=new SSOwnReport();x.setId(5);x.setName("Mall");x.setProjectNr("P1");x.setResultUnitNr(null);SSOwnReportRow h1=new SSOwnReportRow();h1.setType(SSHeadingType.HEADING1);h1.setHeading("Intäkter");SSAccount acc=new SSAccount(3001);acc.setDescription("Försäljning");acc.setActive(true);Map<SSMonth,BigDecimal> budget=new HashMap<>();budget.put(new SSMonth(LocalDate.of(2026,1,1),LocalDate.of(2026,1,31)),new BigDecimal("100.00"));budget.put(new SSMonth(LocalDate.of(2026,2,1),LocalDate.of(2026,2,28)),null);SSOwnReportAccountRow a1=new SSOwnReportAccountRow(acc,budget);h1.getAccountRows().add(a1);SSOwnReportRow h2=new SSOwnReportRow();h2.setType(null);h2.setHeading("");h2.getAccountRows().add(new SSOwnReportAccountRow(null,null));x.getHeadings().add(h1);x.getHeadings().add(h2);return x;}
 private static Connection conn(String n)throws Exception{Class.forName("org.hsqldb.jdbcDriver");Connection c=DriverManager.getConnection("jdbc:hsqldb:mem:"+n+"_"+UUID.randomUUID(),"sa","");c.setAutoCommit(false);return c;}
 private static void schema(Connection c)throws Exception{try(InputStream in=OwnReportStagingConverterTest.class.getResourceAsStream("/sql/create_tables.sql")){String sql=new String(Objects.requireNonNull(in).readAllBytes(),StandardCharsets.UTF_8);try(var p=c.createStatement()){for(String y:sql.split(";"))if(!y.isBlank())p.execute(y.trim());}c.commit();}}
 private static void insertCompany(Connection c,SSNewCompany x)throws Exception{try(var p=c.prepareStatement("INSERT INTO tbl_company (id,company) VALUES (?,?)")){p.setInt(1,x.getId());p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static void insertScoped(Connection c,String t,String col,String key,Object x)throws Exception{try(var p=c.prepareStatement("INSERT INTO "+t+" (number,"+col+",companyid) VALUES (?,?,1)")){p.setString(1,key);p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static long count(Connection c,String t)throws Exception{try(var s=c.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM "+t)){r.next();return r.getLong(1);}}
}
