package org.fribok.bookkeeping.dataformat;
import org.junit.jupiter.api.Test;
import se.swedsoft.bookkeeping.data.*;
import se.swedsoft.bookkeeping.data.common.*;
import java.io.InputStream;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.sql.*;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;
class PaymentStagingConverterTest{
 @Test void roundTripsInAndOutpaymentsWithBothVouchers()throws Exception{try(Connection legacy=conn("payment_legacy");Connection target=conn("payment_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany company=new SSNewCompany();company.setId(1);insertCompany(legacy,company);
   SSInpayment in=new SSInpayment();in.setNumber(11);in.setLocalDate(LocalDate.of(2026,2,1));in.setText("");in.setEntered(false);Map<SSDefaultAccount,Integer> def=new HashMap<>();def.put(SSDefaultAccount.InPayment,1930);def.put(SSDefaultAccount.Tax1,null);in.setDefaultAccounts(def);
   SSInpaymentRow inRow=new SSInpaymentRow();inRow.setInvoiceNr(42);SSCurrency eur=new SSCurrency("EUR","Euro");eur.setExchangeRate(new BigDecimal("11.25"));inRow.setInvoiceCurrency(eur);inRow.setInvoiceCurrencyRate(new BigDecimal("11.250"));inRow.setValue(new BigDecimal("100.00"));inRow.setCurrencyRate(new BigDecimal("1.00"));in.getRows().add(inRow);
   SSVoucher main=new SSVoucher(0);main.setLocalDate(LocalDate.of(2026,2,1));main.setDescription("");SSVoucherRow vr=new SSVoucherRow();vr.setAccountNr(1930);vr.setDebet(new BigDecimal("100.00"));vr.setLocalEditedDate(LocalDateTime.of(2026,3,29,2,30));vr.setEditedSignature("vb");main.addVoucherRow(vr);in.setVoucher(main);SSVoucher diff=new SSVoucher(1);diff.setLocalDate(null);diff.setDescription(null);in.setDifference(diff);
   try(var p=legacy.prepareStatement("INSERT INTO tbl_inpayment (id,number,inpayment,companyid) VALUES (?,?,?,?)")){p.setInt(1,1);p.setInt(2,11);p.setObject(3,in);p.setInt(4,1);p.executeUpdate();}
   SSOutpayment out=new SSOutpayment();out.setNumber(22);out.setLocalDate(null);out.setText(null);out.setEntered(true);out.setDefaultAccounts(new HashMap<>());SSOutpaymentRow outRow=new SSOutpaymentRow();outRow.setInvoiceNr(7);outRow.setValue(new BigDecimal("-5.5"));out.getRows().add(outRow);SSVoucher ov=new SSVoucher(0);ov.addVoucherRow(new SSVoucherRow());out.setVoucher(ov);out.setDifference(null);
   try(var p=legacy.prepareStatement("INSERT INTO tbl_outpayment (id,number,outpayment,companyid) VALUES (?,?,?,?)")){p.setInt(1,2);p.setInt(2,22);p.setObject(3,out);p.setInt(4,1);p.executeUpdate();legacy.commit();}
   new AccountingCoreStagingConverter().convert(legacy,target);
   var result=new PaymentStagingConverter().convert(legacy,target);
   assertThat(result.sourceFingerprint()).isEqualTo(result.destinationFingerprint());assertThat(result.payments()).isEqualTo(2);assertThat(result.rows()).isEqualTo(2);assertThat(result.defaultAccounts()).isEqualTo(2);assertThat(result.voucherRows()).isEqualTo(2);assertThat(result.daylightSavingGapAdjustments()).isEqualTo(1);
   assertThat(count(target,"inpayment")).isEqualTo(1);assertThat(count(target,"outpayment")).isEqualTo(1);assertThat(count(target,"inpayment_voucher")).isEqualTo(2);assertThat(count(target,"outpayment_voucher")).isEqualTo(1);}}
 @Test void rejectsInpaymentKeyMismatch()throws Exception{try(Connection legacy=conn("payment_bad_legacy");Connection target=conn("payment_bad_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany c=new SSNewCompany();c.setId(1);insertCompany(legacy,c);new AccountingCoreStagingConverter().convert(legacy,target);SSInpayment x=new SSInpayment();x.setNumber(2);try(var p=legacy.prepareStatement("INSERT INTO tbl_inpayment (id,number,inpayment,companyid) VALUES (?,?,?,?)")){p.setInt(1,1);p.setInt(2,1);p.setObject(3,x);p.setInt(4,1);p.executeUpdate();legacy.commit();}assertThatThrownBy(()->new PaymentStagingConverter().convert(legacy,target)).isInstanceOf(SQLException.class).hasMessageContaining("Inpayment key/object mismatch");}}
 private static Connection conn(String n)throws Exception{Class.forName("org.hsqldb.jdbcDriver");Connection c=DriverManager.getConnection("jdbc:hsqldb:mem:"+n+"_"+UUID.randomUUID(),"sa","");c.setAutoCommit(false);return c;}
 private static void schema(Connection c)throws Exception{try(InputStream in=PaymentStagingConverterTest.class.getResourceAsStream("/sql/create_tables.sql")){String sql=new String(Objects.requireNonNull(in).readAllBytes(),StandardCharsets.UTF_8);try(var p=c.createStatement()){for(String x:sql.split(";"))if(!x.isBlank())p.execute(x.trim());}c.commit();}}
 private static void insertCompany(Connection c,SSNewCompany x)throws Exception{try(var p=c.prepareStatement("INSERT INTO tbl_company (id,company) VALUES (?,?)")){p.setInt(1,x.getId());p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static long count(Connection c,String t)throws Exception{try(var s=c.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM "+t)){r.next();return r.getLong(1);}}
}
