package org.fribok.bookkeeping.dataformat;
import org.junit.jupiter.api.Test;
import se.swedsoft.bookkeeping.data.*;
import se.swedsoft.bookkeeping.data.base.SSSaleRow;
import se.swedsoft.bookkeeping.data.common.*;
import java.io.InputStream;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.sql.*;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;
class PeriodicInvoiceStagingConverterTest{
 @Test void roundTripsTemplateInstancesAndAddedFlags()throws Exception{try(Connection legacy=conn("periodic_legacy");Connection target=conn("periodic_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany company=new SSNewCompany();company.setId(1);insertCompany(legacy,company);SSNewProject project=new SSNewProject("P1","Project",null);insertScoped(legacy,"tbl_project","project","P1",project);SSNewResultUnit unit=new SSNewResultUnit("R1","Unit");insertScoped(legacy,"tbl_resultunit","resultunit","R1",unit);
   SSPeriodicInvoice periodic=periodic();try(var p=legacy.prepareStatement("INSERT INTO tbl_periodicinvoice (id,number,periodicinvoice,companyid) VALUES (?,?,?,?)")){p.setInt(1,5);p.setInt(2,7);p.setObject(3,periodic);p.setInt(4,1);p.executeUpdate();legacy.commit();}
   new AccountingCoreStagingConverter().convert(legacy,target);new AccountingDimensionsStagingConverter().convert(legacy,target);insertLookup(legacy,target,"currency","EUR");insertLookup(legacy,target,"payment_term","30");insertLookup(legacy,target,"delivery_term","FK");insertLookup(legacy,target,"delivery_way","P");insertUnit(target,"st");
   var result=new PeriodicInvoiceStagingConverter().convert(legacy,target);
   assertThat(result.sourceFingerprint()).isEqualTo(result.destinationFingerprint());assertThat(result.periodics()).isEqualTo(1);assertThat(result.templateRows()).isEqualTo(2);assertThat(result.instances()).isEqualTo(2);assertThat(result.instanceRows()).isEqualTo(3);assertThat(count(target,"periodic_invoice")).isEqualTo(1);assertThat(count(target,"periodic_invoice_instance")).isEqualTo(2);}}
 @Test void rejectsTableAndObjectNumberMismatch()throws Exception{try(Connection legacy=conn("periodic_bad_legacy");Connection target=conn("periodic_bad_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany c=new SSNewCompany();c.setId(1);insertCompany(legacy,c);new AccountingCoreStagingConverter().convert(legacy,target);SSPeriodicInvoice x=new SSPeriodicInvoice();x.setNumber(2);try(var p=legacy.prepareStatement("INSERT INTO tbl_periodicinvoice (id,number,periodicinvoice,companyid) VALUES (?,?,?,?)")){p.setInt(1,5);p.setInt(2,1);p.setObject(3,x);p.setInt(4,1);p.executeUpdate();legacy.commit();}assertThatThrownBy(()->new PeriodicInvoiceStagingConverter().convert(legacy,target)).isInstanceOf(SQLException.class).hasMessageContaining("key/object mismatch");}}
 private static SSPeriodicInvoice periodic(){SSPeriodicInvoice p=new SSPeriodicInvoice();p.setNumber(7);p.setLocalDate(LocalDate.of(2026,1,1));p.setCount(2);p.setPeriod(1);p.setDescription("");p.setLocalPeriodStart(LocalDate.of(2026,1,1));p.setLocalPeriodEnd(LocalDate.of(2026,1,31));p.setAppendPeriod(true);p.setAppendInformation(true);p.setInformation("Detta är faktura [FAK] av [TOT].");
  SSInvoice template=new SSInvoice();template.setNumber(null);template.setLocalDate(null);template.setCustomerNr("K1");template.setCustomerName("");template.setOurContactPerson("Vi");template.setYourContactPerson("Ni");template.setCurrency(new SSCurrency("EUR","Euro"));template.getCurrency().setExchangeRate(new BigDecimal("11.25"));template.setPaymentTerm(new SSPaymentTerm("30","30 dagar"));template.setDeliveryTerm(new SSDeliveryTerm("FK","Fritt"));template.setDeliveryWay(new SSDeliveryWay("P","Post"));template.setTaxFree(false);template.setText("");template.setTaxRate1(new BigDecimal("25.00"));template.setTaxRate2(null);template.setTaxRate3(new BigDecimal("6"));template.setEuSaleCommodity(true);template.setEuSaleYhirdPartCommodity(false);template.setPrinted(false);template.setType(null);template.setCurrencyRate(new BigDecimal("1.12300"));template.setYourOrderNumber(null);template.setOCRNumber(null);template.setEntered(false);template.setNumRemainders(0);template.setInterestInvoiced(false);template.setStockInfluencing(true);template.setOrderNumbers(null);
  SSSaleRow r1=new SSSaleRow();r1.setProductNr("A");r1.setDescription("");r1.setUnitprice(new BigDecimal("10.125"));r1.setQuantity(new BigDecimal("2"));r1.setUnit(new SSUnit("st","styck"));r1.setDiscount(null);r1.setTaxCode(SSTaxCode.TAXRATE_1);r1.setAccountNr(3001);r1.setProjectNr("P1");r1.setResultUnitNr("R1");SSSaleRow r2=new SSSaleRow();r2.setProductNr(null);r2.setDescription(null);r2.setQuantity(null);template.setRows(r1,r2);p.setTemplate(template);
  SSInvoice i1=new SSInvoice(template);i1.setNumber(1);SSSaleRow i1row=new SSSaleRow();i1row.setProductNr("A");i1row.setDescription("Period 1");i1row.setUnitprice(new BigDecimal("10.125"));i1row.setQuantity(BigDecimal.ONE);i1.setRows(i1row);SSInvoice i2=new SSInvoice(template);i2.setNumber(2);i2.setRows(r1,r2);
  p.getInvoices().add(i1);p.getInvoices().add(i2);p.setAdded(i1);p.setNotAdded(i2);return p;}
 private static Connection conn(String n)throws Exception{Class.forName("org.hsqldb.jdbcDriver");Connection c=DriverManager.getConnection("jdbc:hsqldb:mem:"+n+"_"+UUID.randomUUID(),"sa","");c.setAutoCommit(false);return c;}
 private static void schema(Connection c)throws Exception{try(InputStream in=PeriodicInvoiceStagingConverterTest.class.getResourceAsStream("/sql/create_tables.sql")){String sql=new String(Objects.requireNonNull(in).readAllBytes(),StandardCharsets.UTF_8);try(var p=c.createStatement()){for(String x:sql.split(";"))if(!x.isBlank())p.execute(x.trim());}c.commit();}}
 private static void insertCompany(Connection c,SSNewCompany x)throws Exception{try(var p=c.prepareStatement("INSERT INTO tbl_company (id,company) VALUES (?,?)")){p.setInt(1,x.getId());p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static void insertScoped(Connection c,String t,String col,String key,Object x)throws Exception{try(var p=c.prepareStatement("INSERT INTO "+t+" (number,"+col+",companyid) VALUES (?,?,1)")){p.setString(1,key);p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static void insertLookup(Connection legacy,Connection target,String table,String key)throws Exception{String targetTable,legacyTable,column;switch(table){case "currency":targetTable="currency";legacyTable="tbl_currency";column="currency";break;case "payment_term":targetTable="payment_term";legacyTable="tbl_paymentterm";column="paymentterm";break;case "delivery_term":targetTable="delivery_term";legacyTable="tbl_deliveryterm";column="deliveryterm";break;default:targetTable="delivery_way";legacyTable="tbl_deliveryway";column="deliveryway";}try(var r=legacy.createStatement();var rs=r.executeQuery("SELECT "+column+" FROM "+legacyTable+" WHERE "+("currency".equals(table)?"code":"name")+"='"+key+"'");var s=target.prepareStatement("INSERT INTO "+targetTable+" "+("currency".equals(table)?"(code,description,exchange_rate) VALUES (?,?,?)":"(name,description) VALUES (?,?)"))){if(!rs.next()){s.setString(1,key);s.setString(2,"");if("currency".equals(table))s.setBigDecimal(3,BigDecimal.ONE);}else{Object o=rs.getObject(1);if(o instanceof SSCurrency c){s.setString(1,c.getName());s.setString(2,c.getDescription());s.setBigDecimal(3,c.getExchangeRate());}else if(o instanceof SSPaymentTerm x){s.setString(1,x.getName());s.setString(2,x.getDescription());}else if(o instanceof SSDeliveryTerm x){s.setString(1,x.getName());s.setString(2,x.getDescription());}else{SSDeliveryWay x=(SSDeliveryWay)o;s.setString(1,x.getName());s.setString(2,x.getDescription());}}s.executeUpdate();target.commit();}}
 private static void insertUnit(Connection target,String name)throws Exception{try(var s=target.prepareStatement("INSERT INTO unit_definition (name,description) VALUES (?,?)")){s.setString(1,name);s.setString(2,"");s.executeUpdate();target.commit();}}
 private static long count(Connection c,String t)throws Exception{try(var s=c.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM "+t)){r.next();return r.getLong(1);}}
}
