package org.fribok.bookkeeping.dataformat;
import org.junit.jupiter.api.Test;
import se.swedsoft.bookkeeping.data.*;
import se.swedsoft.bookkeeping.data.common.*;
import java.io.InputStream;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.sql.*;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;
class PurchaseOrderStagingConverterTest{
 @Test void roundTripsAllPurchaseOrderFields()throws Exception{try(Connection legacy=conn("po_legacy");Connection target=conn("po_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany company=new SSNewCompany();company.setId(1);insertCompany(legacy,company);
   SSPurchaseOrder order=order();try(var p=legacy.prepareStatement("INSERT INTO tbl_purchaseorder (id,number,purchaseorder,companyid) VALUES (?,?,?,?)")){p.setInt(1,1);p.setInt(2,order.getNumber());p.setObject(3,order);p.setInt(4,1);p.executeUpdate();legacy.commit();}
   new AccountingCoreStagingConverter().convert(legacy,target);
   var result=new PurchaseOrderStagingConverter().convert(legacy,target);
   assertThat(result.sourceFingerprint()).isEqualTo(result.destinationFingerprint());assertThat(result.orders()).isEqualTo(1);assertThat(result.addresses()).isEqualTo(2);assertThat(result.defaultAccounts()).isEqualTo(2);assertThat(result.rows()).isEqualTo(2);
   assertThat(count(target,"purchase_order")).isEqualTo(1);assertThat(count(target,"purchase_order_row")).isEqualTo(2);}}
 @Test void rejectsKeyMismatch()throws Exception{try(Connection legacy=conn("po_bad_legacy");Connection target=conn("po_bad_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany c=new SSNewCompany();c.setId(1);insertCompany(legacy,c);new AccountingCoreStagingConverter().convert(legacy,target);SSPurchaseOrder x=new SSPurchaseOrder();x.setNumber(2);try(var p=legacy.prepareStatement("INSERT INTO tbl_purchaseorder (id,number,purchaseorder,companyid) VALUES (?,?,?,?)")){p.setInt(1,1);p.setInt(2,1);p.setObject(3,x);p.setInt(4,1);p.executeUpdate();legacy.commit();}assertThatThrownBy(()->new PurchaseOrderStagingConverter().convert(legacy,target)).isInstanceOf(SQLException.class).hasMessageContaining("Purchase-order key/object mismatch");}}
 private static SSPurchaseOrder order(){SSPurchaseOrder x=new SSPurchaseOrder();x.setNumber(30);x.setLocalDate(LocalDate.of(2026,7,1));x.setLocalEstimatedDelivery(null);x.setSupplierNr("L1");x.setSupplierName("");x.setPaymentTerm(new SSPaymentTerm("30","30 dagar"));x.setDeliveryTerm(new SSDeliveryTerm("FVL","Fritt lager"));x.setDeliveryWay(new SSDeliveryWay("B","Bil"));x.setOurContact("Vi");x.setYourContact("Ni");SSCurrency dkk=new SSCurrency("DKK","Danska");x.setCurrency(dkk);x.setCurrencyRate(new BigDecimal("1.5000"));x.setText("");x.setPrinted(true);x.setStockInfluencing(false);x.setInvoiceNr(55);x.setDeliveryAddress(new SSAddress("Vi","Gatan","","1","Ort","SE"));x.setSupplierAddress(new SSAddress("De","Vägen","C/O","2","Ort2","DK"));Map<SSDefaultAccount,Integer>a=new HashMap<>();a.put(SSDefaultAccount.Purchases,4010);a.put(SSDefaultAccount.SupplierDebt,null);x.setDefaultAccounts(a);SSPurchaseOrderRow r1=new SSPurchaseOrderRow();r1.setProductNr("A");r1.setDescription("");r1.setSupplierArticleNr("LX");r1.setUnitPrice(new BigDecimal("7.50"));r1.setQuantity(-2);r1.setUnit(new SSUnit("st","styck"));r1.setAccountNr(4010);SSPurchaseOrderRow r2=new SSPurchaseOrderRow();x.getRows().add(r1);x.getRows().add(r2);return x;}
 private static Connection conn(String n)throws Exception{Class.forName("org.hsqldb.jdbcDriver");Connection c=DriverManager.getConnection("jdbc:hsqldb:mem:"+n+"_"+UUID.randomUUID(),"sa","");c.setAutoCommit(false);return c;}
 private static void schema(Connection c)throws Exception{try(InputStream in=PurchaseOrderStagingConverterTest.class.getResourceAsStream("/sql/create_tables.sql")){String sql=new String(Objects.requireNonNull(in).readAllBytes(),StandardCharsets.UTF_8);try(var p=c.createStatement()){for(String y:sql.split(";"))if(!y.isBlank())p.execute(y.trim());}c.commit();}}
 private static void insertCompany(Connection c,SSNewCompany x)throws Exception{try(var p=c.prepareStatement("INSERT INTO tbl_company (id,company) VALUES (?,?)")){p.setInt(1,x.getId());p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static long count(Connection c,String t)throws Exception{try(var s=c.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM "+t)){r.next();return r.getLong(1);}}
}
