package org.fribok.bookkeeping.dataformat;
import org.junit.jupiter.api.Test;
import se.swedsoft.bookkeeping.data.*;
import se.swedsoft.bookkeeping.data.base.SSSaleRow;
import se.swedsoft.bookkeeping.data.common.*;
import java.io.InputStream;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.sql.*;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;
class SaleDocumentStagingConverterTest{
 @Test void roundTripsOrderAndTenderSnapshots()throws Exception{try(Connection legacy=conn("sale_legacy");Connection target=conn("sale_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany company=new SSNewCompany();company.setId(1);insertCompany(legacy,company);SSNewProject project=new SSNewProject("P1","Project",null);insertScoped(legacy,"tbl_project","project","P1",project);
   SSOrder order=order();try(var p=legacy.prepareStatement("INSERT INTO tbl_order (id,number,iorder,companyid) VALUES (?,?,?,?)")){p.setInt(1,1);p.setInt(2,order.getNumber());p.setObject(3,order);p.setInt(4,1);p.executeUpdate();}
   SSTender tender=tender();try(var p=legacy.prepareStatement("INSERT INTO tbl_tender (id,number,tender,companyid) VALUES (?,?,?,?)")){p.setInt(1,2);p.setInt(2,tender.getNumber());p.setObject(3,tender);p.setInt(4,1);p.executeUpdate();legacy.commit();}
   new AccountingCoreStagingConverter().convert(legacy,target);new AccountingDimensionsStagingConverter().convert(legacy,target);
   var result=new SaleDocumentStagingConverter().convert(legacy,target);
   assertThat(result.sourceFingerprint()).isEqualTo(result.destinationFingerprint());assertThat(result.documents()).isEqualTo(2);assertThat(result.addresses()).isEqualTo(4);assertThat(result.defaultAccounts()).isEqualTo(2);assertThat(result.rows()).isEqualTo(2);
   assertThat(count(target,"customer_order")).isEqualTo(1);assertThat(count(target,"tender")).isEqualTo(1);assertThat(count(target,"customer_order_row")).isEqualTo(1);assertThat(count(target,"tender_row")).isEqualTo(1);}}
 @Test void rejectsOrderKeyMismatch()throws Exception{try(Connection legacy=conn("sale_bad_legacy");Connection target=conn("sale_bad_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany c=new SSNewCompany();c.setId(1);insertCompany(legacy,c);new AccountingCoreStagingConverter().convert(legacy,target);SSOrder x=new SSOrder();x.setNumber(2);try(var p=legacy.prepareStatement("INSERT INTO tbl_order (id,number,iorder,companyid) VALUES (?,?,?,?)")){p.setInt(1,1);p.setInt(2,1);p.setObject(3,x);p.setInt(4,1);p.executeUpdate();legacy.commit();}assertThatThrownBy(()->new SaleDocumentStagingConverter().convert(legacy,target)).isInstanceOf(SQLException.class).hasMessageContaining("Order key/object mismatch");}}
 private static SSOrder order(){SSOrder x=new SSOrder();x.setNumber(10);x.setLocalDate(LocalDate.of(2026,5,1));x.setCustomerNr("K1");x.setCustomerName("");x.setOurContactPerson("Vi");x.setYourContactPerson("Ni");x.setDelayInterest(new BigDecimal("12.5"));x.setCurrency(new SSCurrency("EUR","Euro"));x.setCurrencyRate(new BigDecimal("11.2500"));x.setPaymentTerm(new SSPaymentTerm("30","30 dagar"));x.setDeliveryTerm(new SSDeliveryTerm("FK","Fritt"));x.setDeliveryWay(new SSDeliveryWay("P","Post"));x.setTaxFree(false);x.setText("");x.setTaxRate1(new BigDecimal("25"));x.setTaxRate2(null);x.setTaxRate3(new BigDecimal("6"));x.setEuSaleCommodity(true);x.setEuSaleYhirdPartCommodity(false);x.setPrinted(true);x.setYourOrderNumber("O1");x.setEstimatedDelivery("2 dagar");x.setInvoiceNr(42);x.setPeriodicInvoiceNr(7);x.setPurchaseOrder(null);x.setHideUnitprice(true);x.setInvoiceAddress(new SSAddress("F","Gata","","1","Ort","SE"));x.setDeliveryAddress(new SSAddress("L","Väg","C/O","2","Ort2","SE"));Map<SSDefaultAccount,Integer>a=new HashMap<>();a.put(SSDefaultAccount.Sales,3001);x.setDefaultAccounts(a);SSSaleRow r=new SSSaleRow();r.setProductNr("A");r.setDescription("");r.setUnitprice(new BigDecimal("10.125"));r.setQuantity(new BigDecimal("-2.5"));r.setUnit(new SSUnit("st","styck"));r.setProjectNr("P1");x.setRows(r);return x;}
 private static SSTender tender(){SSTender x=new SSTender();x.setNumber(20);x.setLocalDate(null);x.setLocalExpires(LocalDate.of(2026,6,30));x.setCustomerNr(null);x.setCustomerName(null);x.setTaxFree(true);x.setPrinted(false);x.setCurrencyRate(null);x.setPaymentTerm(null);x.setDeliveryTerm(null);x.setDeliveryWay(null);x.setCurrency(null);Map<SSDefaultAccount,Integer>a=new HashMap<>();a.put(SSDefaultAccount.Cash,null);x.setDefaultAccounts(a);SSSaleRow r=new SSSaleRow();x.setRows(r);x.setInvoiceAddress(new SSAddress("T","Gata","","3","Ort","SE"));x.setDeliveryAddress(new SSAddress("TL","Väg","","4","Ort","SE"));return x;}
 private static Connection conn(String n)throws Exception{Class.forName("org.hsqldb.jdbcDriver");Connection c=DriverManager.getConnection("jdbc:hsqldb:mem:"+n+"_"+UUID.randomUUID(),"sa","");c.setAutoCommit(false);return c;}
 private static void schema(Connection c)throws Exception{try(InputStream in=SaleDocumentStagingConverterTest.class.getResourceAsStream("/sql/create_tables.sql")){String sql=new String(Objects.requireNonNull(in).readAllBytes(),StandardCharsets.UTF_8);try(var p=c.createStatement()){for(String y:sql.split(";"))if(!y.isBlank())p.execute(y.trim());}c.commit();}}
 private static void insertCompany(Connection c,SSNewCompany x)throws Exception{try(var p=c.prepareStatement("INSERT INTO tbl_company (id,company) VALUES (?,?)")){p.setInt(1,x.getId());p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static void insertScoped(Connection c,String t,String col,String key,Object x)throws Exception{try(var p=c.prepareStatement("INSERT INTO "+t+" (number,"+col+",companyid) VALUES (?,?,1)")){p.setString(1,key);p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static long count(Connection c,String t)throws Exception{try(var s=c.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM "+t)){r.next();return r.getLong(1);}}
}
