package org.fribok.bookkeeping.dataformat;
import org.junit.jupiter.api.Test;
import se.swedsoft.bookkeeping.data.*;
import se.swedsoft.bookkeeping.data.common.*;
import java.io.InputStream;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.sql.*;import java.time.*;import java.util.*;
import static org.assertj.core.api.Assertions.*;
class SupplierInvoiceStagingConverterTest{
 @Test void roundTripsRowsAccountsAndBothVouchers()throws Exception{try(Connection legacy=conn("suppinv_legacy");Connection target=conn("suppinv_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany company=new SSNewCompany();company.setId(1);insertCompany(legacy,company);SSNewProject project=new SSNewProject("P1","Project",null);insertScoped(legacy,"tbl_project","project","P1",project);SSNewResultUnit unit=new SSNewResultUnit("R1","Unit");insertScoped(legacy,"tbl_resultunit","resultunit","R1",unit);
   SSSupplierInvoice invoice=invoice();try(var p=legacy.prepareStatement("INSERT INTO tbl_supplierinvoice (id,number,supplierinvoice,companyid) VALUES (?,?,?,?)")){p.setInt(1,3);p.setInt(2,55);p.setObject(3,invoice);p.setInt(4,1);p.executeUpdate();legacy.commit();}
   new AccountingCoreStagingConverter().convert(legacy,target);new AccountingDimensionsStagingConverter().convert(legacy,target);
   var result=new SupplierInvoiceStagingConverter().convert(legacy,target);
   assertThat(result.sourceFingerprint()).isEqualTo(result.destinationFingerprint());assertThat(result.invoices()).isEqualTo(1);assertThat(result.rows()).isEqualTo(2);assertThat(result.defaultAccounts()).isEqualTo(2);assertThat(result.vouchers()).isEqualTo(2);assertThat(result.voucherRows()).isEqualTo(2);assertThat(result.daylightSavingOverlapResolutions()).isEqualTo(1);
   assertThat(count(target,"supplier_invoice")).isEqualTo(1);assertThat(count(target,"supplier_invoice_row")).isEqualTo(2);assertThat(count(target,"supplier_invoice_voucher")).isEqualTo(2);}}
 @Test void rejectsTableAndObjectNumberMismatch()throws Exception{try(Connection legacy=conn("suppinv_bad_legacy");Connection target=conn("suppinv_bad_target")){schema(legacy);new SchemaMigrationRunner(Clock.fixed(Instant.EPOCH,ZoneOffset.UTC)).migrate(target,NormalizedSchemaMigrations.load());SSNewCompany c=new SSNewCompany();c.setId(1);insertCompany(legacy,c);new AccountingCoreStagingConverter().convert(legacy,target);SSSupplierInvoice x=new SSSupplierInvoice();x.setNumber(2);try(var p=legacy.prepareStatement("INSERT INTO tbl_supplierinvoice (id,number,supplierinvoice,companyid) VALUES (?,?,?,?)")){p.setInt(1,3);p.setInt(2,1);p.setObject(3,x);p.setInt(4,1);p.executeUpdate();legacy.commit();}assertThatThrownBy(()->new SupplierInvoiceStagingConverter().convert(legacy,target)).isInstanceOf(SQLException.class).hasMessageContaining("Supplier-invoice key/object mismatch");}}
 private static SSSupplierInvoice invoice(){SSSupplierInvoice x=new SSSupplierInvoice();x.setNumber(55);x.setLocalDate(LocalDate.of(2026,10,25));x.setLocalDueDate(null);x.setPaymentTerm(new SSPaymentTerm("30","30 dagar"));x.setSupplierNr("L1");x.setSupplierName("");x.setReferencenumber(null);x.setCurrency(new SSCurrency("DKK","Danska"));x.getCurrency().setExchangeRate(new BigDecimal("1.5"));x.setCurrencyRate(new BigDecimal("1.5000"));x.setTaxSum(new BigDecimal("25.00"));x.setRoundingSum(null);x.setEntered(false);x.setBGCEntered(true);x.setStockInfluencing(false);Map<SSDefaultAccount,Integer>a=new HashMap<>();a.put(SSDefaultAccount.Purchases,4010);a.put(SSDefaultAccount.SupplierDebt,null);x.setDefaultAccounts(a);
  SSSupplierInvoiceRow r1=new SSSupplierInvoiceRow();r1.setProductNr("A");r1.setDescription("");r1.setUnitprice(new BigDecimal("10.125"));r1.setQuantity(-2);r1.setUnit(new SSUnit("st","styck"));r1.setUnitFreight(new BigDecimal("0.00"));r1.setAccountNr(4010);r1.setProjectNr("P1");r1.setResultUnitNr("R1");SSSupplierInvoiceRow r2=new SSSupplierInvoiceRow();r2.setProductNr(null);r2.setQuantity(null);x.setRows(Arrays.asList(r1,r2));
  SSVoucher main=new SSVoucher(0);main.setLocalDate(LocalDate.of(2026,10,25));main.setDescription("");SSVoucherRow vr=new SSVoucherRow();vr.setAccountNr(2440);vr.setCredit(new BigDecimal("125.00"));vr.setLocalEditedDate(LocalDateTime.of(2026,10,25,2,30));vr.setEditedSignature("vb");main.addVoucherRow(vr);x.setVoucher(main);
  SSVoucher correction=new SSVoucher(1);correction.setLocalDate(null);correction.setDescription(null);SSVoucherRow cr=new SSVoucherRow();cr.setDebet(new BigDecimal("5.0"));correction.addVoucherRow(cr);x.setCorrection(correction);return x;}
 private static Connection conn(String n)throws Exception{Class.forName("org.hsqldb.jdbcDriver");Connection c=DriverManager.getConnection("jdbc:hsqldb:mem:"+n+"_"+UUID.randomUUID(),"sa","");c.setAutoCommit(false);return c;}
 private static void schema(Connection c)throws Exception{try(InputStream in=SupplierInvoiceStagingConverterTest.class.getResourceAsStream("/sql/create_tables.sql")){String sql=new String(Objects.requireNonNull(in).readAllBytes(),StandardCharsets.UTF_8);try(var p=c.createStatement()){for(String y:sql.split(";"))if(!y.isBlank())p.execute(y.trim());}c.commit();}}
 private static void insertCompany(Connection c,SSNewCompany x)throws Exception{try(var p=c.prepareStatement("INSERT INTO tbl_company (id,company) VALUES (?,?)")){p.setInt(1,x.getId());p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static void insertScoped(Connection c,String t,String col,String key,Object x)throws Exception{try(var p=c.prepareStatement("INSERT INTO "+t+" (number,"+col+",companyid) VALUES (?,?,1)")){p.setString(1,key);p.setObject(2,x);p.executeUpdate();c.commit();}}
 private static long count(Connection c,String t)throws Exception{try(var s=c.createStatement();var r=s.executeQuery("SELECT COUNT(*) FROM "+t)){r.next();return r.getLong(1);}}
}
