package org.fribok.bookkeeping.dataformat;

import se.swedsoft.bookkeeping.data.SSAddress;
import se.swedsoft.bookkeeping.data.SSSupplier;

import java.sql.*;
import java.util.*;

/** Converts the complete company-scoped supplier register into normalized staging tables. */
public final class SupplierRegisterStagingConverter {
    public ConversionResult convert(Connection legacy,Connection normalized)throws SQLException{Snapshot source=readLegacy(Objects.requireNonNull(legacy));SemanticFingerprint sf=fingerprint(source);try{writeNormalized(Objects.requireNonNull(normalized),source);Snapshot destination=readNormalized(normalized);SemanticFingerprint df=fingerprint(destination);List<String>d=sf.differences(df);if(!d.isEmpty()){normalized.rollback();throw new SQLException("Supplier-register staging fingerprint mismatch: "+String.join("; ",d));}normalized.commit();return new ConversionResult(sf,df,source.suppliers.size(),source.addresses.size());}catch(SQLException|RuntimeException e){normalized.rollback();throw e;}}
    public SemanticFingerprint fingerprintNormalized(Connection c)throws SQLException{return fingerprint(readNormalized(c));}

    private static Snapshot readLegacy(Connection c)throws SQLException{Snapshot s=new Snapshot();query(c,"SELECT id,companyid,number,supplier FROM tbl_supplier ORDER BY companyid,id",r->{int id=r.getInt(1),company=r.getInt(2);String key=r.getString(3);SSSupplier x=(SSSupplier)r.getObject(4);if(!Objects.equals(key,x.getNumber()))throw new SQLException("Supplier key/object mismatch for legacy id "+id+": table="+key+", object="+x.getNumber());s.suppliers.add(new Supplier(id,company,key,x.getName(),x.getPhone1(),x.getPhone2(),x.getTelefax(),x.getEMail(),x.getHomepage(),x.getRegistrationNumber(),x.getYourContact(),x.getOurContact(),x.getOurCustomerNr(),x.getBankgiro(),x.getPlusgiro(),x.getOutpaymentNumber(),x.getStoredCurrency()==null?null:x.getStoredCurrency().getName(),name(x.getPaymentTerm()),name(x.getDeliveryTerm()),name(x.getDeliveryWay()),x.getComment()));addAddress(s,id,company,x.getAddress());});s.sort();return s;}

    private static void writeNormalized(Connection c,Snapshot snapshot)throws SQLException{for(Supplier r:snapshot.suppliers){try(PreparedStatement p=c.prepareStatement("INSERT INTO supplier (legacy_id,company_id,number,name,phone,phone_2,telefax,email,homepage,registration_number,supplier_contact_person,our_contact_person,our_customer_number,bankgiro,plusgiro,outpayment_number,currency_code,payment_term_name,delivery_term_name,delivery_way_name,comment) SELECT ?,id,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM company WHERE legacy_id=?",Statement.RETURN_GENERATED_KEYS)){int i=1;p.setInt(i++,r.legacyId);for(String v:r.firstStrings())p.setString(i++,v);setInteger(p,i++,r.outpaymentNumber);for(String v:r.lookupStrings())p.setString(i++,v);p.setString(i++,r.comment);p.setInt(i,r.companyLegacyId);if(p.executeUpdate()!=1)throw new SQLException("Missing company "+r.companyLegacyId+" for supplier "+r.legacyId);r.normalizedId=key(p);}}Map<Integer,Long>ids=new HashMap<>();for(Supplier r:snapshot.suppliers)ids.put(r.legacyId,r.normalizedId);for(Address r:snapshot.addresses){Long id=ids.get(r.supplierLegacyId);if(id==null)throw new SQLException("Missing supplier mapping "+r.supplierLegacyId);try(PreparedStatement p=c.prepareStatement("INSERT INTO supplier_address VALUES (?,?,?,?,?,?,?,?)")){p.setLong(1,id);p.setLong(2,companyId(c,r.companyLegacyId));int i=3;for(String v:r.values())p.setString(i++,v);p.executeUpdate();}}}

    private static Snapshot readNormalized(Connection c)throws SQLException{Snapshot s=new Snapshot();query(c,"SELECT x.id,x.legacy_id,c.legacy_id,x.number,x.name,x.phone,x.phone_2,x.telefax,x.email,x.homepage,x.registration_number,x.supplier_contact_person,x.our_contact_person,x.our_customer_number,x.bankgiro,x.plusgiro,x.outpayment_number,x.currency_code,x.payment_term_name,x.delivery_term_name,x.delivery_way_name,x.comment FROM supplier x JOIN company c ON c.id=x.company_id ORDER BY c.legacy_id,x.id",r->{Supplier x=new Supplier(r.getInt(2),r.getInt(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11),r.getString(12),r.getString(13),r.getString(14),r.getString(15),r.getString(16),nullableInteger(r,17),r.getString(18),r.getString(19),r.getString(20),r.getString(21),r.getString(22));x.normalizedId=r.getLong(1);s.suppliers.add(x);});query(c,"SELECT x.legacy_id,c.legacy_id,a.name,a.address_line_1,a.address_line_2,a.postal_code,a.city,a.country FROM supplier_address a JOIN supplier x ON x.id=a.supplier_id JOIN company c ON c.id=a.company_id ORDER BY c.legacy_id,x.legacy_id",r->s.addresses.add(new Address(r.getInt(1),r.getInt(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8))));s.sort();return s;}

    private static SemanticFingerprint fingerprint(Snapshot s){SemanticFingerprintBuilder b=new SemanticFingerprintBuilder();var d=b.domain("suppliers");for(Supplier r:s.suppliers){var w=d.startRecord(r.companyLegacyId+"/"+r.legacyId).writeInteger(r.legacyId).writeInteger(r.companyLegacyId);for(String v:r.firstStrings())w.writeString(v);w.writeInteger(r.outpaymentNumber);for(String v:r.lookupStrings())w.writeString(v);w.writeString(r.comment);}d.finish();var a=b.domain("supplier-addresses");for(Address r:s.addresses){var w=a.startRecord(r.companyLegacyId+"/"+r.supplierLegacyId).writeInteger(r.supplierLegacyId).writeInteger(r.companyLegacyId);for(String v:r.values())w.writeString(v);}a.finish();return b.finish();}
    private static void addAddress(Snapshot s,int supplier,int company,SSAddress a){if(a!=null)s.addresses.add(new Address(supplier,company,a.getName(),a.getAddress1(),a.getAddress2(),a.getZipCode(),a.getCity(),a.getCountry()));}
    private static String name(Object v){if(v instanceof se.swedsoft.bookkeeping.data.common.SSPaymentTerm x)return x.getName();if(v instanceof se.swedsoft.bookkeeping.data.common.SSDeliveryTerm x)return x.getName();if(v instanceof se.swedsoft.bookkeeping.data.common.SSDeliveryWay x)return x.getName();return null;}
    private static long key(PreparedStatement p)throws SQLException{try(ResultSet r=p.getGeneratedKeys()){if(!r.next())throw new SQLException("Missing generated supplier key");return r.getLong(1);}}
    private static long companyId(Connection c,int legacy)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT id FROM company WHERE legacy_id=?")){p.setInt(1,legacy);try(ResultSet r=p.executeQuery()){if(!r.next())throw new SQLException("Missing company "+legacy);return r.getLong(1);}}}
    private static void setInteger(PreparedStatement p,int i,Integer v)throws SQLException{if(v==null)p.setNull(i,Types.INTEGER);else p.setInt(i,v);}private static Integer nullableInteger(ResultSet r,int i)throws SQLException{int v=r.getInt(i);return r.wasNull()?null:v;}private static void query(Connection c,String sql,SqlRow f)throws SQLException{try(Statement p=c.createStatement();ResultSet r=p.executeQuery(sql)){while(r.next())f.accept(r);}}
    public record ConversionResult(SemanticFingerprint sourceFingerprint,SemanticFingerprint destinationFingerprint,long suppliers,long addresses){}@FunctionalInterface private interface SqlRow{void accept(ResultSet r)throws SQLException;}
    private static final class Supplier{final int legacyId,companyLegacyId;final String number,name,phone,phone2,telefax,email,homepage,registration,supplierContact,ourContact,ourCustomerNumber,bankgiro,plusgiro;final Integer outpaymentNumber;final String currency,paymentTerm,deliveryTerm,deliveryWay,comment;long normalizedId;Supplier(int legacyId,int companyLegacyId,String number,String name,String phone,String phone2,String telefax,String email,String homepage,String registration,String supplierContact,String ourContact,String ourCustomerNumber,String bankgiro,String plusgiro,Integer outpaymentNumber,String currency,String paymentTerm,String deliveryTerm,String deliveryWay,String comment){this.legacyId=legacyId;this.companyLegacyId=companyLegacyId;this.number=number;this.name=name;this.phone=phone;this.phone2=phone2;this.telefax=telefax;this.email=email;this.homepage=homepage;this.registration=registration;this.supplierContact=supplierContact;this.ourContact=ourContact;this.ourCustomerNumber=ourCustomerNumber;this.bankgiro=bankgiro;this.plusgiro=plusgiro;this.outpaymentNumber=outpaymentNumber;this.currency=currency;this.paymentTerm=paymentTerm;this.deliveryTerm=deliveryTerm;this.deliveryWay=deliveryWay;this.comment=comment;}List<String>firstStrings(){return Arrays.asList(number,name,phone,phone2,telefax,email,homepage,registration,supplierContact,ourContact,ourCustomerNumber,bankgiro,plusgiro);}List<String>lookupStrings(){return Arrays.asList(currency,paymentTerm,deliveryTerm,deliveryWay);}}
    private record Address(int supplierLegacyId,int companyLegacyId,String name,String line1,String line2,String postal,String city,String country){List<String>values(){return Arrays.asList(name,line1,line2,postal,city,country);}}
    private static final class Snapshot{final List<Supplier>suppliers=new ArrayList<>();final List<Address>addresses=new ArrayList<>();void sort(){suppliers.sort(Comparator.comparingInt((Supplier r)->r.companyLegacyId).thenComparingInt(r->r.legacyId));addresses.sort(Comparator.comparingInt(Address::companyLegacyId).thenComparingInt(Address::supplierLegacyId));}}
}
