package org.fribok.bookkeeping.service.vat;
import se.swedsoft.bookkeeping.calc.math.*; import se.swedsoft.bookkeeping.calc.util.SSVATUtil; import se.swedsoft.bookkeeping.data.*; import se.swedsoft.bookkeeping.data.system.SSDB;
import java.math.*; import java.time.LocalDate; import java.util.*;
/** Headless VAT report and settlement use cases. */
public final class VatService {
 private final SSDB db; public VatService(SSDB db){this.db=db;}
 public VatReport report(LocalDate f,LocalDate t){if(f==null||t==null||t.isBefore(f))throw new IllegalArgumentException("VAT period is invalid");List<SSVoucher> v=SSVoucherMath.getVouchers(db.getVouchers(),f,t);Map<SSAccount,BigDecimal> c=SSVoucherMath.getCreditMinusDebetSum(v),d=SSVoucherMath.getDebetMinusCreditSum(v);List<VatReportBox>b=new ArrayList<>();
  add(b,5,"MP1,MP2,MP3,PTOG",sum(c,"MP1","MP2","MP3","PTOG"));add(b,10,"U1,UVL",sum(c,"U1","UVL"));add(b,11,"U2",sum(c,"U2"));add(b,12,"U3",sum(c,"U3"));add(b,20,"VFEU",sum(d,"VFEU"));add(b,21,"TFEU",sum(d,"TFEU"));add(b,22,"TFFU",sum(d,"TFFU"));add(b,30,"U1MI,UEU,UTFU",sum(c,"U1MI","UEU","UTFU"));add(b,31,"U2MI",sum(c,"U2MI"));add(b,32,"U3MI",sum(c,"U3MI"));add(b,48,"I,IVL",sum(d,"I","IVL"));add(b,50,"IBU,IBU1,IBU2,IBU3",sum(c,"IBU","IBU1","IBU2","IBU3"));add(b,60,"UI1",sum(c,"UI1"));add(b,61,"UI2",sum(c,"UI2"));add(b,62,"UI3",sum(c,"UI3"));BigDecimal vat=box(b,10).add(box(b,11)).add(box(b,12)).add(box(b,30)).add(box(b,31)).add(box(b,32)).add(box(b,60)).add(box(b,61)).add(box(b,62)).subtract(box(b,48));add(b,49,"R1,R2",vat);return new VatReport(f,t,b,vat);}
 public VatSettlementPlan plan(LocalDate f,LocalDate t){VatReport r=report(f,t);List<SSAccount>a=db.getAccounts();SSAccount r1=SSAccountMath.getAccountWithVATCode(a,"R1",fallback(1650)).orElseThrow(()->new IllegalStateException("VAT receivable account is ambiguous or missing"));SSAccount r2=SSAccountMath.getAccountWithVATCode(a,"R2",fallback(2650)).orElseThrow(()->new IllegalStateException("VAT payable account is ambiguous or missing"));SSAccount rounding=SSAccountMath.getAccountWithVATCode(a,"A",fallback(3740)).orElseThrow(()->new IllegalStateException("VAT rounding account is ambiguous or missing"));return new VatSettlementPlan(r,SSVATUtil.generateVATVoucher("VAT",f,t,r1,r2,rounding));}
 public VatSettlementResult commit(VatSettlementPlan p){if(p.voucher().getRows().isEmpty())throw new IllegalArgumentException("VAT settlement has no rows");db.addVoucher(p.voucher(),false);return new VatSettlementResult(p.voucher().getNumber());}
 private SSAccount fallback(int number){SSAccountPlan p=db.getCurrentAccountPlan();return p==null?null:p.getAccount(number);}
 private BigDecimal sum(Map<SSAccount,BigDecimal>m,String...codes){BigDecimal x=BigDecimal.ZERO;Set<String>s=Set.of(codes);for(SSAccount a:db.getAccounts())if(a.getVATCode()!=null&&s.contains(a.getVATCode())&&m.get(a)!=null)x=x.add(m.get(a).setScale(0,RoundingMode.DOWN));return x;}
 private static void add(List<VatReportBox>b,int n,String c,BigDecimal a){b.add(new VatReportBox(n,c,a));} private static BigDecimal box(List<VatReportBox>b,int n){return b.stream().filter(x->x.number()==n).findFirst().orElseThrow().amount();}
}
