package org.fribok.bookkeeping.service.openingbalance;
import se.swedsoft.bookkeeping.calc.SSBalanceCalculator; import se.swedsoft.bookkeeping.calc.math.SSAccountMath; import se.swedsoft.bookkeeping.data.*; import se.swedsoft.bookkeeping.data.system.SSDB; import java.math.*; import java.util.*;
/** Opening balance validation, replacement, and carry-forward. */
public final class OpeningBalanceService {private final SSDB db;public OpeningBalanceService(SSDB d){db=d;}
 public OpeningBalancePlan current(SSNewAccountingYear y){return plan(y,y.getInBalance());}
 public OpeningBalancePlan validate(SSNewAccountingYear y,Map<Integer,BigDecimal> input){Map<SSAccount,BigDecimal> values=new LinkedHashMap<>();for(var e:input.entrySet()){SSAccount a=y.getAccountPlan().getAccount(e.getKey());if(a==null)throw new IllegalArgumentException("Account not found: "+e.getKey());if(!SSAccountMath.isBalanceAccount(a,y))throw new IllegalArgumentException("Not a balance account: "+e.getKey());if(e.getValue()==null)throw new IllegalArgumentException("Amount missing for account "+e.getKey());values.put(a,e.getValue());}OpeningBalancePlan p=plan(y,values);if(p.difference().setScale(2,RoundingMode.HALF_UP).signum()!=0)throw new IllegalArgumentException("Opening balance is not balanced");return p;}
 public OpeningBalancePlan replace(SSNewAccountingYear y,Map<Integer,BigDecimal> input){OpeningBalancePlan p=validate(y,input);Map<SSAccount,BigDecimal> values=new HashMap<>();for(var e:p.balances()){values.put(y.getAccountPlan().getAccount(e.account()),e.amount());}y.setInBalance(values);db.updateAccountingYear(y);return p;}
 public OpeningBalancePlan carryForward(SSNewAccountingYear from,SSNewAccountingYear to,boolean commit){Map<SSAccount,BigDecimal> out=SSBalanceCalculator.getOutBalance(from);Map<Integer,BigDecimal> input=new LinkedHashMap<>();for(var e:out.entrySet()){SSAccount target=to.getAccountPlan().getAccount(e.getKey().getNumber());if(target!=null&&SSAccountMath.isBalanceAccount(target,to)&&e.getValue().signum()!=0)input.put(target.getNumber(),e.getValue());}OpeningBalancePlan p=validate(to,input);if(commit)replace(to,input);return p;}
 private OpeningBalancePlan plan(SSNewAccountingYear y,Map<SSAccount,BigDecimal> values){List<OpeningBalanceEntry> rows=values.entrySet().stream().filter(e->e.getValue()!=null&&e.getValue().signum()!=0).sorted(Map.Entry.comparingByKey(Comparator.comparing(SSAccount::getNumber))).map(e->new OpeningBalanceEntry(e.getKey().getNumber(),e.getKey().getDescription(),e.getValue())).toList();BigDecimal debit=rows.stream().map(OpeningBalanceEntry::amount).filter(x->x.signum()>0).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal credit=rows.stream().map(OpeningBalanceEntry::amount).filter(x->x.signum()<0).map(BigDecimal::abs).reduce(BigDecimal.ZERO,BigDecimal::add);return new OpeningBalancePlan(rows,debit,credit,debit.subtract(credit));}
}
