-- Customer credit invoices retain their own sale and voucher snapshots.
CREATE TABLE customer_credit_invoice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER, crediting_invoice_number INTEGER,
  invoice_date DATE, due_date DATE,
  customer_number VARCHAR(255), customer_name VARCHAR(255),
  our_contact_person VARCHAR(255), customer_contact_person VARCHAR(255),
  delay_interest DECIMAL(100,30), currency_code VARCHAR(255),
  payment_term_name VARCHAR(255), delivery_term_name VARCHAR(255), delivery_way_name VARCHAR(255),
  tax_free BOOLEAN NOT NULL, invoice_text VARCHAR(16384),
  tax_rate_1 DECIMAL(100,30), tax_rate_2 DECIMAL(100,30), tax_rate_3 DECIMAL(100,30),
  eu_sale_commodity BOOLEAN NOT NULL, eu_sale_third_party_commodity BOOLEAN NOT NULL,
  printed BOOLEAN NOT NULL, invoice_type VARCHAR(32), currency_rate DECIMAL(100,30),
  customer_order_number VARCHAR(1024), ocr_number VARCHAR(255), entered BOOLEAN NOT NULL,
  reminder_count INTEGER NOT NULL, interest_invoiced BOOLEAN NOT NULL,
  stock_influencing BOOLEAN NOT NULL, order_numbers VARCHAR(4096),
  CONSTRAINT fk_credit_invoice_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT fk_credit_invoice_currency FOREIGN KEY(currency_code) REFERENCES currency(code),
  CONSTRAINT fk_credit_invoice_payment FOREIGN KEY(payment_term_name) REFERENCES payment_term(name),
  CONSTRAINT fk_credit_invoice_delivery_term FOREIGN KEY(delivery_term_name) REFERENCES delivery_term(name),
  CONSTRAINT fk_credit_invoice_delivery_way FOREIGN KEY(delivery_way_name) REFERENCES delivery_way(name),
  CONSTRAINT uq_credit_invoice_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_credit_invoice_company_number ON customer_credit_invoice(company_id,number);

CREATE TABLE customer_credit_invoice_address (
  credit_invoice_id BIGINT NOT NULL, company_id BIGINT NOT NULL,
  address_type VARCHAR(16) NOT NULL, name VARCHAR(255),
  address_line_1 VARCHAR(1024), address_line_2 VARCHAR(1024), postal_code VARCHAR(64),
  city VARCHAR(255), country VARCHAR(255), PRIMARY KEY(credit_invoice_id,address_type),
  CONSTRAINT fk_credit_address_scope FOREIGN KEY(credit_invoice_id,company_id)
    REFERENCES customer_credit_invoice(id,company_id),
  CONSTRAINT ck_credit_address_type CHECK(address_type IN ('invoice','delivery'))
);
CREATE TABLE customer_credit_invoice_default_account (
  credit_invoice_id BIGINT NOT NULL, account_type VARCHAR(64) NOT NULL, account_number INTEGER,
  PRIMARY KEY(credit_invoice_id,account_type),
  CONSTRAINT fk_credit_default_account FOREIGN KEY(credit_invoice_id) REFERENCES customer_credit_invoice(id)
);
CREATE TABLE customer_credit_invoice_row (
  credit_invoice_id BIGINT NOT NULL, company_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), description VARCHAR(4096), unit_price DECIMAL(100,30),
  quantity DECIMAL(100,30), unit_name VARCHAR(255), discount DECIMAL(100,30), tax_code VARCHAR(32),
  account_number INTEGER, project_number VARCHAR(255), result_unit_number VARCHAR(255),
  PRIMARY KEY(credit_invoice_id,row_number),
  CONSTRAINT fk_credit_row_scope FOREIGN KEY(credit_invoice_id,company_id)
    REFERENCES customer_credit_invoice(id,company_id),
  CONSTRAINT fk_credit_row_unit FOREIGN KEY(unit_name) REFERENCES unit_definition(name),
  CONSTRAINT fk_credit_row_project FOREIGN KEY(company_id,project_number) REFERENCES project(company_id,number),
  CONSTRAINT fk_credit_row_result FOREIGN KEY(company_id,result_unit_number) REFERENCES result_unit(company_id,number)
);
CREATE TABLE customer_credit_invoice_voucher (
  credit_invoice_id BIGINT PRIMARY KEY, number INTEGER NOT NULL, voucher_date DATE,
  description VARCHAR(4096), CONSTRAINT fk_credit_voucher FOREIGN KEY(credit_invoice_id)
    REFERENCES customer_credit_invoice(id)
);
CREATE TABLE customer_credit_invoice_voucher_row (
  credit_invoice_id BIGINT NOT NULL, row_number INTEGER NOT NULL, account_number INTEGER,
  project_number VARCHAR(255), result_unit_number VARCHAR(255), debit DECIMAL(100,30),
  credit DECIMAL(100,30), edited_at TIMESTAMP WITH TIME ZONE, edited_signature VARCHAR(255),
  crossed BOOLEAN NOT NULL, added BOOLEAN NOT NULL, PRIMARY KEY(credit_invoice_id,row_number),
  CONSTRAINT fk_credit_voucher_row FOREIGN KEY(credit_invoice_id)
    REFERENCES customer_credit_invoice_voucher(credit_invoice_id)
);
