-- Customer inpayments and supplier outpayments with rows, main and difference vouchers.
CREATE TABLE inpayment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER,
  payment_date DATE,
  text VARCHAR(4096),
  entered BOOLEAN NOT NULL,
  CONSTRAINT fk_inpayment_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT uq_inpayment_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_inpayment_company_number ON inpayment(company_id,number);
CREATE TABLE inpayment_row (
  inpayment_id BIGINT NOT NULL, row_number INTEGER NOT NULL, invoice_number INTEGER,
  invoice_currency_code VARCHAR(255), invoice_currency_rate DECIMAL(100,30),
  value DECIMAL(100,30), currency_rate DECIMAL(100,30),
  PRIMARY KEY(inpayment_id,row_number),
  CONSTRAINT fk_inpayment_row_parent FOREIGN KEY(inpayment_id) REFERENCES inpayment(id),
  CONSTRAINT fk_inpayment_row_currency FOREIGN KEY(invoice_currency_code) REFERENCES currency(code)
);
CREATE TABLE inpayment_default_account (
  inpayment_id BIGINT NOT NULL, account_type VARCHAR(64) NOT NULL, account_number INTEGER,
  PRIMARY KEY(inpayment_id,account_type),
  CONSTRAINT fk_inpayment_default_account FOREIGN KEY(inpayment_id) REFERENCES inpayment(id)
);
CREATE TABLE inpayment_voucher (
  inpayment_id BIGINT NOT NULL, voucher_kind VARCHAR(16) NOT NULL, number INTEGER NOT NULL,
  voucher_date DATE, description VARCHAR(4096),
  PRIMARY KEY(inpayment_id,voucher_kind),
  CONSTRAINT fk_inpayment_voucher FOREIGN KEY(inpayment_id) REFERENCES inpayment(id),
  CONSTRAINT ck_inpayment_voucher_kind CHECK(voucher_kind IN ('main','difference'))
);
CREATE TABLE inpayment_voucher_row (
  inpayment_id BIGINT NOT NULL, voucher_kind VARCHAR(16) NOT NULL, row_number INTEGER NOT NULL,
  account_number INTEGER, project_number VARCHAR(255), result_unit_number VARCHAR(255),
  debit DECIMAL(100,30), credit DECIMAL(100,30), edited_at TIMESTAMP WITH TIME ZONE,
  edited_signature VARCHAR(255), crossed BOOLEAN NOT NULL, added BOOLEAN NOT NULL,
  PRIMARY KEY(inpayment_id,voucher_kind,row_number),
  CONSTRAINT fk_inpayment_voucher_row FOREIGN KEY(inpayment_id,voucher_kind)
    REFERENCES inpayment_voucher(inpayment_id,voucher_kind)
);

CREATE TABLE outpayment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER,
  payment_date DATE,
  text VARCHAR(4096),
  entered BOOLEAN NOT NULL,
  CONSTRAINT fk_outpayment_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT uq_outpayment_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_outpayment_company_number ON outpayment(company_id,number);
CREATE TABLE outpayment_row (
  outpayment_id BIGINT NOT NULL, row_number INTEGER NOT NULL, invoice_number INTEGER,
  invoice_currency_code VARCHAR(255), invoice_currency_rate DECIMAL(100,30),
  value DECIMAL(100,30), currency_rate DECIMAL(100,30),
  PRIMARY KEY(outpayment_id,row_number),
  CONSTRAINT fk_outpayment_row_parent FOREIGN KEY(outpayment_id) REFERENCES outpayment(id),
  CONSTRAINT fk_outpayment_row_currency FOREIGN KEY(invoice_currency_code) REFERENCES currency(code)
);
CREATE TABLE outpayment_default_account (
  outpayment_id BIGINT NOT NULL, account_type VARCHAR(64) NOT NULL, account_number INTEGER,
  PRIMARY KEY(outpayment_id,account_type),
  CONSTRAINT fk_outpayment_default_account FOREIGN KEY(outpayment_id) REFERENCES outpayment(id)
);
CREATE TABLE outpayment_voucher (
  outpayment_id BIGINT NOT NULL, voucher_kind VARCHAR(16) NOT NULL, number INTEGER NOT NULL,
  voucher_date DATE, description VARCHAR(4096),
  PRIMARY KEY(outpayment_id,voucher_kind),
  CONSTRAINT fk_outpayment_voucher FOREIGN KEY(outpayment_id) REFERENCES outpayment(id),
  CONSTRAINT ck_outpayment_voucher_kind CHECK(voucher_kind IN ('main','difference'))
);
CREATE TABLE outpayment_voucher_row (
  outpayment_id BIGINT NOT NULL, voucher_kind VARCHAR(16) NOT NULL, row_number INTEGER NOT NULL,
  account_number INTEGER, project_number VARCHAR(255), result_unit_number VARCHAR(255),
  debit DECIMAL(100,30), credit DECIMAL(100,30), edited_at TIMESTAMP WITH TIME ZONE,
  edited_signature VARCHAR(255), crossed BOOLEAN NOT NULL, added BOOLEAN NOT NULL,
  PRIMARY KEY(outpayment_id,voucher_kind,row_number),
  CONSTRAINT fk_outpayment_voucher_row FOREIGN KEY(outpayment_id,voucher_kind)
    REFERENCES outpayment_voucher(outpayment_id,voucher_kind)
);
