-- Supplier invoices with ordered rows, default accounts, and main/correction vouchers.
CREATE TABLE supplier_invoice (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER,
  invoice_date DATE, due_date DATE,
  payment_term_name VARCHAR(255),
  supplier_number VARCHAR(255), supplier_name VARCHAR(255), reference_number VARCHAR(255),
  currency_code VARCHAR(255), currency_rate DECIMAL(100,30),
  tax_sum DECIMAL(100,30), rounding_sum DECIMAL(100,30),
  entered BOOLEAN NOT NULL, bgc_entered BOOLEAN NOT NULL, stock_influencing BOOLEAN NOT NULL,
  CONSTRAINT fk_supplier_invoice_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT fk_supplier_invoice_payment FOREIGN KEY(payment_term_name) REFERENCES payment_term(name),
  CONSTRAINT fk_supplier_invoice_currency FOREIGN KEY(currency_code) REFERENCES currency(code),
  CONSTRAINT uq_supplier_invoice_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_supplier_invoice_company_number ON supplier_invoice(company_id,number);
CREATE TABLE supplier_invoice_row (
  supplier_invoice_id BIGINT NOT NULL, company_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), description VARCHAR(4096), unit_price DECIMAL(100,30),
  quantity INTEGER, unit_name VARCHAR(255), unit_freight DECIMAL(100,30),
  account_number INTEGER, project_number VARCHAR(255), result_unit_number VARCHAR(255),
  PRIMARY KEY(supplier_invoice_id,row_number),
  CONSTRAINT fk_supplier_invoice_row_scope FOREIGN KEY(supplier_invoice_id,company_id)
    REFERENCES supplier_invoice(id,company_id),
  CONSTRAINT fk_supplier_invoice_row_unit FOREIGN KEY(unit_name) REFERENCES unit_definition(name),
  CONSTRAINT fk_supplier_invoice_row_project FOREIGN KEY(company_id,project_number) REFERENCES project(company_id,number),
  CONSTRAINT fk_supplier_invoice_row_result FOREIGN KEY(company_id,result_unit_number) REFERENCES result_unit(company_id,number)
);
CREATE TABLE supplier_invoice_default_account (
  supplier_invoice_id BIGINT NOT NULL, account_type VARCHAR(64) NOT NULL, account_number INTEGER,
  PRIMARY KEY(supplier_invoice_id,account_type),
  CONSTRAINT fk_supplier_invoice_default_account FOREIGN KEY(supplier_invoice_id) REFERENCES supplier_invoice(id)
);
CREATE TABLE supplier_invoice_voucher (
  supplier_invoice_id BIGINT NOT NULL, voucher_kind VARCHAR(16) NOT NULL, number INTEGER NOT NULL,
  voucher_date DATE, description VARCHAR(4096),
  PRIMARY KEY(supplier_invoice_id,voucher_kind),
  CONSTRAINT fk_supplier_invoice_voucher FOREIGN KEY(supplier_invoice_id) REFERENCES supplier_invoice(id),
  CONSTRAINT ck_supplier_invoice_voucher_kind CHECK(voucher_kind IN ('main','correction'))
);
CREATE TABLE supplier_invoice_voucher_row (
  supplier_invoice_id BIGINT NOT NULL, voucher_kind VARCHAR(16) NOT NULL, row_number INTEGER NOT NULL,
  account_number INTEGER, project_number VARCHAR(255), result_unit_number VARCHAR(255),
  debit DECIMAL(100,30), credit DECIMAL(100,30), edited_at TIMESTAMP WITH TIME ZONE,
  edited_signature VARCHAR(255), crossed BOOLEAN NOT NULL, added BOOLEAN NOT NULL,
  PRIMARY KEY(supplier_invoice_id,voucher_kind,row_number),
  CONSTRAINT fk_supplier_invoice_voucher_row FOREIGN KEY(supplier_invoice_id,voucher_kind)
    REFERENCES supplier_invoice_voucher(supplier_invoice_id,voucher_kind)
);
