-- Customer orders and tenders share the SSSale snapshot shape with document-specific fields.
CREATE TABLE customer_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER, sale_date DATE,
  customer_number VARCHAR(255), customer_name VARCHAR(255),
  our_contact_person VARCHAR(255), customer_contact_person VARCHAR(255),
  delay_interest DECIMAL(100,30), currency_code VARCHAR(255), currency_rate DECIMAL(100,30),
  payment_term_name VARCHAR(255), delivery_term_name VARCHAR(255), delivery_way_name VARCHAR(255),
  tax_free BOOLEAN NOT NULL, sale_text VARCHAR(16384),
  tax_rate_1 DECIMAL(100,30), tax_rate_2 DECIMAL(100,30), tax_rate_3 DECIMAL(100,30),
  eu_sale_commodity BOOLEAN NOT NULL, eu_sale_third_party_commodity BOOLEAN NOT NULL,
  printed BOOLEAN NOT NULL,
  customer_order_number VARCHAR(1024), estimated_delivery VARCHAR(255),
  invoice_number INTEGER, periodic_invoice_number INTEGER, purchase_order_number INTEGER,
  hide_unit_price BOOLEAN NOT NULL,
  CONSTRAINT fk_order_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT fk_order_currency FOREIGN KEY(currency_code) REFERENCES currency(code),
  CONSTRAINT fk_order_payment FOREIGN KEY(payment_term_name) REFERENCES payment_term(name),
  CONSTRAINT fk_order_delivery_term FOREIGN KEY(delivery_term_name) REFERENCES delivery_term(name),
  CONSTRAINT fk_order_delivery_way FOREIGN KEY(delivery_way_name) REFERENCES delivery_way(name),
  CONSTRAINT uq_order_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_order_company_number ON customer_order(company_id,number);
CREATE TABLE customer_order_address (
  order_id BIGINT NOT NULL, company_id BIGINT NOT NULL, address_type VARCHAR(16) NOT NULL,
  name VARCHAR(255), address_line_1 VARCHAR(1024), address_line_2 VARCHAR(1024),
  postal_code VARCHAR(64), city VARCHAR(255), country VARCHAR(255),
  PRIMARY KEY(order_id,address_type),
  CONSTRAINT fk_order_address_scope FOREIGN KEY(order_id,company_id)
    REFERENCES customer_order(id,company_id),
  CONSTRAINT ck_order_address_type CHECK(address_type IN ('invoice','delivery'))
);
CREATE TABLE customer_order_default_account (
  order_id BIGINT NOT NULL, account_type VARCHAR(64) NOT NULL, account_number INTEGER,
  PRIMARY KEY(order_id,account_type),
  CONSTRAINT fk_order_default_account FOREIGN KEY(order_id) REFERENCES customer_order(id)
);
CREATE TABLE customer_order_row (
  order_id BIGINT NOT NULL, company_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), description VARCHAR(4096), unit_price DECIMAL(100,30),
  quantity DECIMAL(100,30), unit_name VARCHAR(255), discount DECIMAL(100,30), tax_code VARCHAR(32),
  account_number INTEGER, project_number VARCHAR(255), result_unit_number VARCHAR(255),
  PRIMARY KEY(order_id,row_number),
  CONSTRAINT fk_order_row_scope FOREIGN KEY(order_id,company_id) REFERENCES customer_order(id,company_id),
  CONSTRAINT fk_order_row_unit FOREIGN KEY(unit_name) REFERENCES unit_definition(name),
  CONSTRAINT fk_order_row_project FOREIGN KEY(company_id,project_number) REFERENCES project(company_id,number),
  CONSTRAINT fk_order_row_result FOREIGN KEY(company_id,result_unit_number) REFERENCES result_unit(company_id,number)
);

CREATE TABLE tender (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER, sale_date DATE, expires_on DATE,
  customer_number VARCHAR(255), customer_name VARCHAR(255),
  our_contact_person VARCHAR(255), customer_contact_person VARCHAR(255),
  delay_interest DECIMAL(100,30), currency_code VARCHAR(255), currency_rate DECIMAL(100,30),
  payment_term_name VARCHAR(255), delivery_term_name VARCHAR(255), delivery_way_name VARCHAR(255),
  tax_free BOOLEAN NOT NULL, sale_text VARCHAR(16384),
  tax_rate_1 DECIMAL(100,30), tax_rate_2 DECIMAL(100,30), tax_rate_3 DECIMAL(100,30),
  eu_sale_commodity BOOLEAN NOT NULL, eu_sale_third_party_commodity BOOLEAN NOT NULL,
  printed BOOLEAN NOT NULL, order_number INTEGER,
  CONSTRAINT fk_tender_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT fk_tender_currency FOREIGN KEY(currency_code) REFERENCES currency(code),
  CONSTRAINT fk_tender_payment FOREIGN KEY(payment_term_name) REFERENCES payment_term(name),
  CONSTRAINT fk_tender_delivery_term FOREIGN KEY(delivery_term_name) REFERENCES delivery_term(name),
  CONSTRAINT fk_tender_delivery_way FOREIGN KEY(delivery_way_name) REFERENCES delivery_way(name),
  CONSTRAINT uq_tender_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_tender_company_number ON tender(company_id,number);
CREATE TABLE tender_address (
  tender_id BIGINT NOT NULL, company_id BIGINT NOT NULL, address_type VARCHAR(16) NOT NULL,
  name VARCHAR(255), address_line_1 VARCHAR(1024), address_line_2 VARCHAR(1024),
  postal_code VARCHAR(64), city VARCHAR(255), country VARCHAR(255),
  PRIMARY KEY(tender_id,address_type),
  CONSTRAINT fk_tender_address_scope FOREIGN KEY(tender_id,company_id)
    REFERENCES tender(id,company_id),
  CONSTRAINT ck_tender_address_type CHECK(address_type IN ('invoice','delivery'))
);
CREATE TABLE tender_default_account (
  tender_id BIGINT NOT NULL, account_type VARCHAR(64) NOT NULL, account_number INTEGER,
  PRIMARY KEY(tender_id,account_type),
  CONSTRAINT fk_tender_default_account FOREIGN KEY(tender_id) REFERENCES tender(id)
);
CREATE TABLE tender_row (
  tender_id BIGINT NOT NULL, company_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), description VARCHAR(4096), unit_price DECIMAL(100,30),
  quantity DECIMAL(100,30), unit_name VARCHAR(255), discount DECIMAL(100,30), tax_code VARCHAR(32),
  account_number INTEGER, project_number VARCHAR(255), result_unit_number VARCHAR(255),
  PRIMARY KEY(tender_id,row_number),
  CONSTRAINT fk_tender_row_scope FOREIGN KEY(tender_id,company_id) REFERENCES tender(id,company_id),
  CONSTRAINT fk_tender_row_unit FOREIGN KEY(unit_name) REFERENCES unit_definition(name),
  CONSTRAINT fk_tender_row_project FOREIGN KEY(company_id,project_number) REFERENCES project(company_id,number),
  CONSTRAINT fk_tender_row_result FOREIGN KEY(company_id,result_unit_number) REFERENCES result_unit(company_id,number)
);
