-- Purchase orders with supplier snapshot, two addresses, ordered rows and default accounts.
CREATE TABLE purchase_order (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER, order_date DATE, estimated_delivery_on DATE,
  supplier_number VARCHAR(255), supplier_name VARCHAR(255),
  payment_term_name VARCHAR(255), delivery_term_name VARCHAR(255), delivery_way_name VARCHAR(255),
  our_contact_person VARCHAR(255), supplier_contact_person VARCHAR(255),
  currency_code VARCHAR(255), currency_rate DECIMAL(100,30),
  order_text VARCHAR(16384), printed BOOLEAN NOT NULL, stock_influencing BOOLEAN NOT NULL,
  invoice_number INTEGER,
  CONSTRAINT fk_purchase_order_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT fk_purchase_order_currency FOREIGN KEY(currency_code) REFERENCES currency(code),
  CONSTRAINT fk_purchase_order_payment FOREIGN KEY(payment_term_name) REFERENCES payment_term(name),
  CONSTRAINT fk_purchase_order_delivery_term FOREIGN KEY(delivery_term_name) REFERENCES delivery_term(name),
  CONSTRAINT fk_purchase_order_delivery_way FOREIGN KEY(delivery_way_name) REFERENCES delivery_way(name),
  CONSTRAINT uq_purchase_order_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_purchase_order_company_number ON purchase_order(company_id,number);
CREATE TABLE purchase_order_address (
  purchase_order_id BIGINT NOT NULL, company_id BIGINT NOT NULL, address_type VARCHAR(16) NOT NULL,
  name VARCHAR(255), address_line_1 VARCHAR(1024), address_line_2 VARCHAR(1024),
  postal_code VARCHAR(64), city VARCHAR(255), country VARCHAR(255),
  PRIMARY KEY(purchase_order_id,address_type),
  CONSTRAINT fk_purchase_order_address_scope FOREIGN KEY(purchase_order_id,company_id)
    REFERENCES purchase_order(id,company_id),
  CONSTRAINT ck_purchase_order_address_type CHECK(address_type IN ('delivery','supplier'))
);
CREATE TABLE purchase_order_default_account (
  purchase_order_id BIGINT NOT NULL, account_type VARCHAR(64) NOT NULL, account_number INTEGER,
  PRIMARY KEY(purchase_order_id,account_type),
  CONSTRAINT fk_purchase_order_default_account FOREIGN KEY(purchase_order_id) REFERENCES purchase_order(id)
);
CREATE TABLE purchase_order_row (
  purchase_order_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), description VARCHAR(4096), supplier_article_number VARCHAR(255),
  unit_price DECIMAL(100,30), quantity INTEGER, unit_name VARCHAR(255), account_number INTEGER,
  PRIMARY KEY(purchase_order_id,row_number),
  CONSTRAINT fk_purchase_order_row_parent FOREIGN KEY(purchase_order_id) REFERENCES purchase_order(id),
  CONSTRAINT fk_purchase_order_row_unit FOREIGN KEY(unit_name) REFERENCES unit_definition(name)
);
