-- In/out deliveries and inventory counts: simple headers with ordered product-quantity rows.
CREATE TABLE indelivery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER, delivery_date DATE, delivery_text VARCHAR(4096),
  CONSTRAINT fk_indelivery_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT uq_indelivery_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_indelivery_company_number ON indelivery(company_id,number);
CREATE TABLE indelivery_row (
  indelivery_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), change_quantity INTEGER,
  PRIMARY KEY(indelivery_id,row_number),
  CONSTRAINT fk_indelivery_row_parent FOREIGN KEY(indelivery_id) REFERENCES indelivery(id)
);

CREATE TABLE outdelivery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER, delivery_date DATE, delivery_text VARCHAR(4096),
  CONSTRAINT fk_outdelivery_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT uq_outdelivery_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_outdelivery_company_number ON outdelivery(company_id,number);
CREATE TABLE outdelivery_row (
  outdelivery_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), change_quantity INTEGER,
  PRIMARY KEY(outdelivery_id,row_number),
  CONSTRAINT fk_outdelivery_row_parent FOREIGN KEY(outdelivery_id) REFERENCES outdelivery(id)
);

CREATE TABLE inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER, inventory_date DATE, inventory_text VARCHAR(4096),
  CONSTRAINT fk_inventory_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT uq_inventory_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_inventory_company_number ON inventory(company_id,number);
CREATE TABLE inventory_row (
  inventory_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  product_number VARCHAR(255), stock_quantity INTEGER, change_quantity INTEGER,
  PRIMARY KEY(inventory_id,row_number),
  CONSTRAINT fk_inventory_row_parent FOREIGN KEY(inventory_id) REFERENCES inventory(id)
);
