-- Own reports: report header, ordered heading rows, account rows with account snapshot and budgets.
CREATE TABLE own_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number INTEGER,
  name VARCHAR(255),
  project_number VARCHAR(255),
  result_unit_number VARCHAR(255),
  CONSTRAINT fk_own_report_company FOREIGN KEY(company_id) REFERENCES company(id),
  CONSTRAINT fk_own_report_project FOREIGN KEY(company_id,project_number) REFERENCES project(company_id,number),
  CONSTRAINT fk_own_report_result FOREIGN KEY(company_id,result_unit_number) REFERENCES result_unit(company_id,number),
  CONSTRAINT uq_own_report_id_scope UNIQUE(id,company_id)
);
CREATE INDEX ix_own_report_company_number ON own_report(company_id,number);

CREATE TABLE own_report_heading (
  own_report_id BIGINT NOT NULL, row_number INTEGER NOT NULL,
  heading_type VARCHAR(32), heading VARCHAR(4096),
  PRIMARY KEY(own_report_id,row_number),
  CONSTRAINT fk_own_report_heading FOREIGN KEY(own_report_id) REFERENCES own_report(id)
);

CREATE TABLE own_report_account_row (
  own_report_id BIGINT NOT NULL, heading_row_number INTEGER NOT NULL, row_number INTEGER NOT NULL,
  account_number INTEGER, description VARCHAR(1024), sru_code VARCHAR(64), vat_code VARCHAR(64),
  report_code VARCHAR(64), active BOOLEAN, project_required BOOLEAN, result_unit_required BOOLEAN,
  PRIMARY KEY(own_report_id,heading_row_number,row_number),
  CONSTRAINT fk_own_report_account_parent FOREIGN KEY(own_report_id,heading_row_number)
    REFERENCES own_report_heading(own_report_id,row_number)
);

CREATE TABLE own_report_account_budget (
  own_report_id BIGINT NOT NULL, heading_row_number INTEGER NOT NULL, account_row_number INTEGER NOT NULL,
  period_start DATE NOT NULL, period_end DATE NOT NULL, amount DECIMAL(100,30),
  PRIMARY KEY(own_report_id,heading_row_number,account_row_number,period_start),
  CONSTRAINT fk_own_report_budget_parent FOREIGN KEY(own_report_id,heading_row_number,account_row_number)
    REFERENCES own_report_account_row(own_report_id,heading_row_number,row_number),
  CONSTRAINT ck_own_report_budget_period CHECK(period_start <= period_end)
);
