-- Normalized accounting-core schema. Applied only to a disposable staging catalog.
CREATE TABLE company (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  name VARCHAR(255),
  corporate_id VARCHAR(64),
  vat_number VARCHAR(64),
  currency_code VARCHAR(16)
);

CREATE TABLE accounting_year (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  starts_on DATE,
  ends_on DATE,
  CONSTRAINT fk_year_company FOREIGN KEY (company_id) REFERENCES company(id),
  CONSTRAINT ck_year_dates CHECK (starts_on IS NULL OR ends_on IS NULL OR starts_on <= ends_on),
  CONSTRAINT uq_year_company_dates UNIQUE (company_id, starts_on, ends_on),
  CONSTRAINT uq_year_id_scope UNIQUE (id, company_id)
);

CREATE TABLE account_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accounting_year_id BIGINT NOT NULL UNIQUE,
  legacy_id INTEGER,
  name VARCHAR(255),
  base_name VARCHAR(255),
  assessment_year VARCHAR(32),
  plan_type VARCHAR(32),
  CONSTRAINT fk_plan_year FOREIGN KEY (accounting_year_id) REFERENCES accounting_year(id)
);

CREATE TABLE account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accounting_year_id BIGINT NOT NULL,
  number INTEGER NOT NULL,
  description VARCHAR(1024),
  sru_code VARCHAR(64),
  vat_code VARCHAR(64),
  report_code VARCHAR(64),
  active BOOLEAN NOT NULL,
  project_required BOOLEAN NOT NULL,
  result_unit_required BOOLEAN NOT NULL,
  CONSTRAINT fk_account_year FOREIGN KEY (accounting_year_id) REFERENCES accounting_year(id),
  CONSTRAINT uq_account_year_number UNIQUE (accounting_year_id, number),
  CONSTRAINT uq_account_id_scope UNIQUE (id, accounting_year_id)
);

CREATE TABLE opening_balance (
  accounting_year_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  amount DECIMAL(100, 30) NOT NULL,
  PRIMARY KEY (accounting_year_id, account_id),
  CONSTRAINT fk_opening_year FOREIGN KEY (accounting_year_id) REFERENCES accounting_year(id),
  CONSTRAINT fk_opening_account_scope FOREIGN KEY (account_id, accounting_year_id)
    REFERENCES account(id, accounting_year_id)
);

CREATE TABLE budget_entry (
  accounting_year_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  amount DECIMAL(100, 30),
  PRIMARY KEY (accounting_year_id, account_id, period_start),
  CONSTRAINT fk_budget_year FOREIGN KEY (accounting_year_id) REFERENCES accounting_year(id),
  CONSTRAINT fk_budget_account_scope FOREIGN KEY (account_id, accounting_year_id)
    REFERENCES account(id, accounting_year_id),
  CONSTRAINT ck_budget_period CHECK (period_start <= period_end)
);

CREATE TABLE voucher (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accounting_year_id BIGINT NOT NULL,
  number INTEGER NOT NULL,
  voucher_date DATE,
  description VARCHAR(4096),
  corrects_voucher_id BIGINT,
  corrected_by_voucher_id BIGINT,
  CONSTRAINT uq_voucher_year_number UNIQUE (accounting_year_id, number),
  CONSTRAINT uq_voucher_id_scope UNIQUE (id, accounting_year_id),
  CONSTRAINT fk_voucher_year FOREIGN KEY (accounting_year_id) REFERENCES accounting_year(id),
  CONSTRAINT fk_voucher_corrects_scope FOREIGN KEY (corrects_voucher_id, accounting_year_id)
    REFERENCES voucher(id, accounting_year_id),
  CONSTRAINT fk_voucher_corrected_by_scope FOREIGN KEY (corrected_by_voucher_id, accounting_year_id)
    REFERENCES voucher(id, accounting_year_id),
  CONSTRAINT ck_voucher_not_self_correcting CHECK (
    (corrects_voucher_id IS NULL OR corrects_voucher_id <> id)
    AND (corrected_by_voucher_id IS NULL OR corrected_by_voucher_id <> id)
  )
);

CREATE TABLE voucher_row (
  voucher_id BIGINT NOT NULL,
  accounting_year_id BIGINT NOT NULL,
  row_number INTEGER NOT NULL,
  account_id BIGINT,
  project_number VARCHAR(255),
  result_unit_number VARCHAR(255),
  debit DECIMAL(100, 30),
  credit DECIMAL(100, 30),
  edited_at TIMESTAMP WITH TIME ZONE,
  edited_signature VARCHAR(255),
  crossed BOOLEAN NOT NULL,
  added BOOLEAN NOT NULL,
  PRIMARY KEY (voucher_id, row_number),
  CONSTRAINT fk_row_voucher_scope FOREIGN KEY (voucher_id, accounting_year_id)
    REFERENCES voucher(id, accounting_year_id),
  CONSTRAINT fk_row_account_scope FOREIGN KEY (account_id, accounting_year_id)
    REFERENCES account(id, accounting_year_id),
  CONSTRAINT ck_row_number CHECK (row_number >= 0),
  CONSTRAINT ck_row_side CHECK (debit IS NULL OR credit IS NULL),
  CONSTRAINT ck_row_debit_nonnegative CHECK (debit IS NULL OR debit >= 0),
  CONSTRAINT ck_row_credit_nonnegative CHECK (credit IS NULL OR credit >= 0)
);

CREATE INDEX ix_year_company ON accounting_year(company_id);
CREATE INDEX ix_account_year ON account(accounting_year_id);
CREATE INDEX ix_voucher_year_date ON voucher(accounting_year_id, voucher_date, number);
CREATE INDEX ix_row_account ON voucher_row(account_id);
