-- Company-scoped customer register and its invoice/delivery addresses.
CREATE TABLE customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number VARCHAR(255),
  name VARCHAR(255),
  email VARCHAR(1024),
  phone VARCHAR(255),
  phone_2 VARCHAR(255),
  telefax VARCHAR(255),
  registration_number VARCHAR(255),
  our_contact_person VARCHAR(255),
  customer_contact_person VARCHAR(255),
  vat_number VARCHAR(255),
  bankgiro VARCHAR(255),
  plusgiro VARCHAR(255),
  account_number VARCHAR(255),
  clearing_number VARCHAR(255),
  eu_sale_commodity BOOLEAN NOT NULL,
  eu_sale_third_party_commodity BOOLEAN NOT NULL,
  vat_free_sale BOOLEAN NOT NULL,
  hide_unit_price BOOLEAN NOT NULL,
  invoice_currency_code VARCHAR(255),
  payment_term_name VARCHAR(255),
  delivery_term_name VARCHAR(255),
  delivery_way_name VARCHAR(255),
  credit_limit DECIMAL(100, 30),
  discount DECIMAL(100, 30),
  comment VARCHAR(16384),
  CONSTRAINT fk_customer_company FOREIGN KEY (company_id) REFERENCES company(id),
  CONSTRAINT fk_customer_currency FOREIGN KEY (invoice_currency_code) REFERENCES currency(code),
  CONSTRAINT fk_customer_payment_term FOREIGN KEY (payment_term_name) REFERENCES payment_term(name),
  CONSTRAINT fk_customer_delivery_term FOREIGN KEY (delivery_term_name) REFERENCES delivery_term(name),
  CONSTRAINT fk_customer_delivery_way FOREIGN KEY (delivery_way_name) REFERENCES delivery_way(name),
  CONSTRAINT uq_customer_id_scope UNIQUE (id, company_id)
);

CREATE INDEX ix_customer_company_number ON customer(company_id, number);

CREATE TABLE customer_address (
  customer_id BIGINT NOT NULL,
  company_id BIGINT NOT NULL,
  address_type VARCHAR(16) NOT NULL,
  name VARCHAR(255),
  address_line_1 VARCHAR(1024),
  address_line_2 VARCHAR(1024),
  postal_code VARCHAR(64),
  city VARCHAR(255),
  country VARCHAR(255),
  PRIMARY KEY (customer_id, address_type),
  CONSTRAINT fk_customer_address_scope FOREIGN KEY (customer_id, company_id)
    REFERENCES customer(id, company_id),
  CONSTRAINT ck_customer_address_type CHECK (address_type IN ('invoice', 'delivery'))
);
