-- Company-scoped supplier register and postal address.
CREATE TABLE supplier (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number VARCHAR(255),
  name VARCHAR(255),
  phone VARCHAR(255),
  phone_2 VARCHAR(255),
  telefax VARCHAR(255),
  email VARCHAR(1024),
  homepage VARCHAR(4096),
  registration_number VARCHAR(255),
  supplier_contact_person VARCHAR(255),
  our_contact_person VARCHAR(255),
  our_customer_number VARCHAR(255),
  bankgiro VARCHAR(255),
  plusgiro VARCHAR(255),
  outpayment_number INTEGER,
  currency_code VARCHAR(255),
  payment_term_name VARCHAR(255),
  delivery_term_name VARCHAR(255),
  delivery_way_name VARCHAR(255),
  comment VARCHAR(16384),
  CONSTRAINT fk_supplier_company FOREIGN KEY (company_id) REFERENCES company(id),
  CONSTRAINT fk_supplier_currency FOREIGN KEY (currency_code) REFERENCES currency(code),
  CONSTRAINT fk_supplier_payment_term FOREIGN KEY (payment_term_name) REFERENCES payment_term(name),
  CONSTRAINT fk_supplier_delivery_term FOREIGN KEY (delivery_term_name) REFERENCES delivery_term(name),
  CONSTRAINT fk_supplier_delivery_way FOREIGN KEY (delivery_way_name) REFERENCES delivery_way(name),
  CONSTRAINT uq_supplier_id_scope UNIQUE (id, company_id)
);

CREATE INDEX ix_supplier_company_number ON supplier(company_id, number);

CREATE TABLE supplier_address (
  supplier_id BIGINT PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name VARCHAR(255),
  address_line_1 VARCHAR(1024),
  address_line_2 VARCHAR(1024),
  postal_code VARCHAR(64),
  city VARCHAR(255),
  country VARCHAR(255),
  CONSTRAINT fk_supplier_address_scope FOREIGN KEY (supplier_id, company_id)
    REFERENCES supplier(id, company_id)
);
