-- Company-scoped product register and embedded maps/parcel rows.
CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id INTEGER NOT NULL UNIQUE,
  company_id BIGINT NOT NULL,
  number VARCHAR(255),
  description VARCHAR(4096),
  selling_price DECIMAL(100, 30),
  tax_code VARCHAR(32),
  warehouse_location VARCHAR(255),
  order_point INTEGER,
  order_count INTEGER,
  purchase_price DECIMAL(100, 30),
  stock_price DECIMAL(100, 30),
  unit_freight DECIMAL(100, 30),
  supplier_number VARCHAR(255),
  supplier_product_number VARCHAR(255),
  expired BOOLEAN NOT NULL,
  stock_goods BOOLEAN NOT NULL,
  unit_name VARCHAR(255),
  weight DECIMAL(100, 30),
  volume DECIMAL(100, 30),
  project_number VARCHAR(255),
  result_unit_number VARCHAR(255),
  CONSTRAINT fk_product_company FOREIGN KEY (company_id) REFERENCES company(id),
  CONSTRAINT fk_product_unit FOREIGN KEY (unit_name) REFERENCES unit_definition(name),
  CONSTRAINT fk_product_project FOREIGN KEY (company_id, project_number)
    REFERENCES project(company_id, number),
  CONSTRAINT fk_product_result_unit FOREIGN KEY (company_id, result_unit_number)
    REFERENCES result_unit(company_id, number),
  CONSTRAINT uq_product_id_scope UNIQUE (id, company_id)
);

CREATE INDEX ix_product_company_number ON product(company_id, number);

CREATE TABLE product_description (
  product_id BIGINT NOT NULL,
  locale_tag VARCHAR(255) NOT NULL,
  description VARCHAR(4096),
  PRIMARY KEY (product_id, locale_tag),
  CONSTRAINT fk_product_description FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_default_account (
  product_id BIGINT NOT NULL,
  account_type VARCHAR(64) NOT NULL,
  account_number INTEGER,
  PRIMARY KEY (product_id, account_type),
  CONSTRAINT fk_product_default_account FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE product_component (
  product_id BIGINT NOT NULL,
  row_number INTEGER NOT NULL,
  component_product_number VARCHAR(255),
  description VARCHAR(4096),
  quantity INTEGER,
  PRIMARY KEY (product_id, row_number),
  CONSTRAINT fk_product_component_parent FOREIGN KEY (product_id) REFERENCES product(id),
  CONSTRAINT ck_product_component_row CHECK (row_number >= 0)
);
